/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type {
  User
} from '../myAPI.schemas';


export const getGetUsersIdResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({id: "123", name: "John Doe", age: 42, ...overrideResponse})

