/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  User
} from '../myAPI.schemas';

import {
  getGetUsersIdResponseMock
} from './default.faker.ts';

export { getGetUsersIdResponseMock } from './default.faker.ts';


export const getGetUsersIdMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/users/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUsersIdResponseMock(),
      { status: 200
      })
  }, options)
}
export const getDefaultMock = () => [
  getGetUsersIdMockHandler()
]
